### ISSUE TITLE
Unable to install Kar feature nexus-repository-terraform

### ISSUE THREAD

**Issue by damnski** [davejab/nexus-repository-terraform#18]
Hi,

Could use some advice please on a nexus-repository-terraform startup issue. 

* **What are you trying to do?**
* Trying to get nexus to start with the terraform provider plugin active.

* **What feature or behavior is this required for?**
* terraform provider proxy.

* **How could we solve this issue? (Not knowing is okay!)**
* Dunno

* **Anything else?**
* errors
* 4 14:01:57,188+0000 ERROR [features-2-thread-1] *SYSTEM java.lang.Throwable - org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-repository-terraform; type=karaf.feature; version="[0.0.4,0.0.4]"; filter:="(&(osgi.identity=nexus-repository-terraform)(type=karaf.feature)(version>=0.0.4)(version<=0.0.4))" [caused by: Unable to resolve nexus-repository-terraform/0.0.4: missing requirement [nexus-repository-terraform/0.0.4] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-terraform; type=osgi.bundle; version="[0.0.4,0.0.4]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4: missing requirement [org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.repository.attributes)(version>=3.38.0))" [caused by: Unable to resolve org.sonatype.nexus.repository [255](R 255.0): missing requirement [org.sonatype.nexus.repository [255](R 255.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]]]
2022-08-24 14:01:57,191+0000 ERROR [features-2-thread-1] *SYSTEM java.lang.Throwable - Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve nexus-repository-terraform/0.0.4: missing requirement [nexus-repository-terraform/0.0.4] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-terraform; type=osgi.bundle; version="[0.0.4,0.0.4]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4: missing requirement [org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.repository.attributes)(version>=3.38.0))" [caused by: Unable to resolve org.sonatype.nexus.repository [255](R 255.0): missing requirement [org.sonatype.nexus.repository [255](R 255.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]]
2022-08-24 14:01:57,192+0000 ERROR [features-2-thread-1] *SYSTEM java.lang.Throwable - Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4: missing requirement [org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.repository.attributes)(version>=3.38.0))" [caused by: Unable to resolve org.sonatype.nexus.repository [255](R 255.0): missing requirement [org.sonatype.nexus.repository [255](R 255.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]
2022-08-24 14:01:57,196+0000 WARN [fileinstall-/opt/nexus/nexus-3.38.1-01/deploy] *SYSTEM org.apache.karaf.kar.internal.KarServiceImpl - Unable to install Kar feature nexus-repository-terraform/0.0.4
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-repository-terraform; type=karaf.feature; version="[0.0.4,0.0.4]"; filter:="(&(osgi.identity=nexus-repository-terraform)(type=karaf.feature)(version>=0.0.4)(version<=0.0.4))" [caused by: Unable to resolve nexus-repository-terraform/0.0.4: missing requirement [nexus-repository-terraform/0.0.4] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-terraform; type=osgi.bundle; version="[0.0.4,0.0.4]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4: missing requirement [org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.repository.attributes)(version>=3.38.0))" [caused by: Unable to resolve org.sonatype.nexus.repository [255](R 255.0): missing requirement [org.sonatype.nexus.repository [255](R 255.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]]]
at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve nexus-repository-terraform/0.0.4: missing requirement [nexus-repository-terraform/0.0.4] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-terraform; type=osgi.bundle; version="[0.0.4,0.0.4]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4: missing requirement [org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.repository.attributes)(version>=3.38.0))" [caused by: Unable to resolve org.sonatype.nexus.repository [255](R 255.0): missing requirement [org.sonatype.nexus.repository [255](R 255.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]]
at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
... 12 common frames omitted
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4: missing requirement [org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.repository.attributes)(version>=3.38.0))" [caused by: Unable to resolve org.sonatype.nexus.repository [255](R 255.0): missing requirement [org.sonatype.nexus.repository [255](R 255.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]
at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
... 13 common frames omitted

Thank you,
-dkw

cc @DarthHater @bhamail

**Comment by davejab** [comment]
@damnski can you please confirm the version of Nexus you are using?

**Comment by vrfn** [comment]
I'm running into the same issue with Nexus v3.40.1:
```
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-repository-terraform; 
type=karaf.feature; version="[0.0.5,0.0.5]"; filter:="(&(osgi.identity=nexus-repository-terraform)(type=karaf.feature)(version>=0.0.5)(version<=0.0.5))" 
[caused by: Unable to resolve nexus-repository-terraform/0.0.5: missing requirement [nexus-repository-terraform/0.0.5] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-repository-terraform; type=osgi.bundle; version="[0.0.5,0.0.5]"; resolution:=mandatory 
[caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.5: missing requirement [org.sonatype.nexus.plugins.nexus-repository-terraform/0.0.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.nexus.repository.attributes)(version>=3.38.0))" 
[caused by: Unable to resolve org.sonatype.nexus.repository [252](R 252.0): missing requirement [org.sonatype.nexus.repository [252](R 252.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]]]
```

I'm deploying Nexus using the [official Helm chart](https://artifacthub.io/packages/helm/sonatype/nexus-repository-manager), and interestingly enough when I leave out 
```
INSTALL4J_ADD_VM_PARAMS=-Dnexus.datastore.enabled=true 
```
it works fine. But unfortunately for me there is no way around setting this param.

**Comment by davejab** [comment]
Thanks @vrfn, let me see if i can replicate and fix

**Comment by damnski** [comment]
> @damnski can you please confirm the version of Nexus you are using?

Hi @davejab:

I experienced the error listed above in my OP with:

v0.0.4 of nexus-repository-terraform

nexus prod 3.38.1-01 and 
nexus prod 3.41.1-01

This is on an isolated network - no route, no proxy to Internet.

I've run the same v0.0.0.4 version of the plugin with the following versions with no problem - routable network w/Internet access.
nexus prod 3.38.1-01 and
nexus prod 3.39.0-01

Thanks very much.  
-dkw

**Comment by davejab** [comment]
Thanks @damnski, do you also have `nexus.datastore.enabled=true` configured?

**Comment by damnski** [comment]
> Thanks @damnski, do you also have `nexus.datastore.enabled=true` configured?

I've observed, where the error is occurring, postgresql is configured and `nexus.datastore.enabled=true.`  Where the error is not occurring, it is using the H2 Builtin DB.

**Comment by vrfn** [comment]
[This](https://help.sonatype.com/repomanager3/planning-your-implementation/sql-database-options/feature-availability-for-postgresql-and-h2-databases#FeatureAvailabilityforPostgreSQLandH2Databases-ExternalPlugins) might be relevant (see 'External Plugins')

**Comment by davejab** [comment]
> [This](https://help.sonatype.com/repomanager3/planning-your-implementation/sql-database-options/feature-availability-for-postgresql-and-h2-databases#FeatureAvailabilityforPostgreSQLandH2Databases-ExternalPlugins) might be relevant (see 'External Plugins')

Yes, this is the issue. The plugin is not currently compatible with datastore. It will take me some time to make the required changes.
